apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-app
  namespace: project-fwk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scan-app
  template:
    metadata:
      labels:
        app: scan-app
    spec:
      containers:
      - name: scan-app
        image: scan-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/mydatabase
        - name: SPRING_DATASOURCE_USERNAME
          value: myuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: secret
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: SURICATA_LOG_PATH
          value: /var/log/suricata/eve.json
        - name: SURICATA_LOG_MONITOR_ENABLED
          value: "true"
        - name: TZ
          value: "Africa/Tunis"
        - name: JAVA_TOOL_OPTIONS
          value: "-Delasticsearch.host=elasticsearch -Delasticsearch.port=9200 -Djava.net.preferIPv4Stack=true"
        volumeMounts:
        - name: logs
          mountPath: /var/log/suricata
          readOnly: true
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: suricata-logs
---
apiVersion: v1
kind: Service
metadata:
  name: scan
  namespace: project-fwk
spec:
  type: ClusterIP
  selector:
    app: scan-app
  ports:
  - port: 8080
    targetPort: 8080
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: scan-app
  namespace: project-fwk
spec:
  type: NodePort
  selector:
    app: scan-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30082
    name: https
